name: Build rules files
on:
  workflow_dispatch:
  schedule:
    - cron: "55 23 * * *"
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download Files
        run: |
          wget https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt
          wget https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/proxy-list.txt
      - name: Remove Old Files
        run: |
          rm out/*.txt
      - name: Sed Files
        run: |
          sed s/^/*./ direct-list.txt > out/direct-list.txt
          sed -i '1 r direct-list-head.txt' out/direct-list.txt
          sed s/^/*./ proxy-list.txt > out/proxy-list.txt
          TIME='\;更新时间：$(date "+%Y\-%m\-%d %H:%M:%S")'
          sed -i "1 $TIME" out/direct-list.txt
          sed -i "1 $TIME" out/proxy-list.txt
      - name: Commit
        run: |
          head out/direct-list.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add out/*
          git commit -m "update by actions"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
